stages:
  - Test And Build App
<<<<<<< HEAD
  - Release App

image: repo.splunk.com/splunk/infra/phantom_apps_tester:latest
=======


image: repo.splunk.com/splunk/infra/phantom_apps_builder:latest
>>>>>>> master

before_script:
  - mkdir -p -m 700 ~/.ssh && echo -e $APP_DEPLOY_KEY > ~/.ssh/app_deploy_key

test:
  stage: Test And Build App
<<<<<<< HEAD
  script: make test
  after_script:
    - make upload
=======
  image: repo.splunk.com/splunk/infra/phantom_apps_tester:latest
  script: make test
  after_script:
    - make upload
  except:
    - tags
>>>>>>> master

build:
  stage: Test And Build App
  script: make build
<<<<<<< HEAD
  image: repo.splunk.com/splunk/infra/phantom_apps_builder:latest
  only:
    - next
    - /^beta\/.+/
    - master
=======
  only:
    - next
    - /^beta\/.+/
>>>>>>> master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Bumped up the version/
      - $CI_COMMIT_MESSAGE =~ /^\[no-build\]/

release:
<<<<<<< HEAD
  stage: Release App
  script: make release
  only:
    - master
=======
  stage: Test And Build App
  script: make release
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Bumped up the version/
      - $CI_COMMIT_MESSAGE =~ /^\[no-build\]/
>>>>>>> master
